### ISSUE TITLE
About --adv and "PGD" in generation part

### ISSUE THREAD

**Issue by CHR-ray** [ZJZAC/Poison-Ink#6]
When I am replicating your code, I found that for the training of generator, if I train incrementally with --rot then --crop then --flip and do poisoning, the ASR is high and stable, but once I continue to train generator with --adv the final result's ASR drops a lot. And I found the log of training generator shows that the Loss_H is high (around 10^3 ~ 10^4 all the time, for all other settings Loss_H is much lower).

So my question is that is --adv necessary? or should I change the default parameters? (I keep all of them except changing --rot --crop --flip for incremental training)

And also I see this:

advdir = "/public/zhangjie/ECCV_2020/backdoor/data_processing_zk/data/cifar10_vgg19_totensor_norm_LR0.01/adv_PGD-8/test"

When I generate the poisoned samples, I cannot find this folder and cannot understand why you use PGD (since I find no clue in the paper), so I remove that part in my experiments.

Is this PGD step important to make ASR high? (And how did you do that? can you provide the script)

**Comment by ZJZAC** [comment]
First, sorry for late feedback due to the overwhelmed academic duties.

Clarification: incremental learning means using --rot; then --rot --flip, wherein --rot shall be preserved for maintaining robustness for the previous augmentation.

Besides, using adv loss will induce a trade-off between visual quality and the ASR. Thus, you can decrease the weight of adv loss for maintaining ASR.

BTW, PGD is not specific selected and just due to common use for classification tasks. We did not try other options. You can try it yourself.

Last, Thanks for your interest on our work.

**Comment by zsaba** [comment]
does this adv_dir mean the images generated from other attacks compared with it like badnets? as in your "test" folder there are other attacks files exist.

**Comment by zsaba** [comment]
or you mean we have to create this folder  in which images with PGD attack are included??

**Comment by ZJZAC** [comment]
adv_folder is used for the adaptive defense, which dose not belong to default setting, thus, just ignore it.

**Comment by zsaba** [comment]
ok. thank you for your response
